### ISSUE TITLE
No error message is shown for a URL that won't show

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/widget-web-page#100]
### What Happens 

- When I embed this URL https://www.fireeye.com/cyber-map/threat-map.html it doesn't show in the Widget and there is no error message to tell me what the problem is.

### What Should Happen 

- When I embed this URL I should see an error message that says: The owner of the Web Page at the URL provided does not allow the page to be embedded within an iFrame. If possible, please contact the Web Page owner to discuss.

### Steps 

- Will attach example Presentation to the card.

**Comment by santiagonoguez** [comment]
Solved in latest branch.
