### ISSUE TITLE
Content in Web Page Widget is sandboxed and cannot be interacted with

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/widget-web-page#103]
### What is the expected behavior?
Interactive elements in the Web Page Widget can be used by touching them on an interactive Display.  

### What is the actual behavior?
Interactive elements in the Web Page Widget are sandboxed and do not react to touch or mouse clicks.  See the example linked in the related card.

### What steps can be taken to replicate the problem?
1. Create a presentation and add the Web Page Widget.
2. Run the web page linked in the related card in the Web Page Widget.
3. Click Preview
4. Try to interact with any elements of the web page.

**Comment by sheadarlison** [comment]
Closing, not a defect
