### ISSUE TITLE
Web Page Widget does not show error message for specific pages

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/widget-web-page#104]
### What is the expected behavior?
When you add http://m.ginlong.com/main.html to the Web Page Widget, it should tell you that it cannot be embedded in an iFrame.

### What is the actual behavior?
It shows no error message in the Widget, so the user is confused why it won't show in the Presentation.

### What steps can be taken to replicate the problem?
Add that page to the Web Page Widget.

**Comment by santiagonoguez** [comment]
The page is being loaded correctly, but there is something in its logic that is preventing it to be shown. This is being closed, as this is related to the code in the page itself and not to some improper handling of HTTP headers. Not a bug.

@robb-price @sheadarlison @stulees
