### ISSUE TITLE
Embedded charts in published google spreadsheets do not load in the web page/html widgets on Displays

### ISSUE THREAD

**Issue by kaden-rise** [Rise-Vision/widget-web-page#106]
**Expected Behavior**
Charts contained in published Google Spreadsheets should load when added to the web page/html widgets.

**Actual Behavior**
The spreadsheet itself loads, but the chart doesn't.

**Steps to reproduce**
1. Create a Google Spreadsheet with an embedded chart
2. Publish that Google Spreadsheet to the web
3. In your test Presentation, insert the link to the published Spreadsheet into a Web Page Widget, or iframe in the HTML Widget
4.  Save and Publish the test Presentation and Schedule the test Presentation to your Display.

**Other notes**
The chart loads when you preview the Presentation from apps.risevision.com, but Displays do not load the chart.

**Comment by stulees** [comment]
@kaden-rise Can you specify the Player / Platforms this was tested on? Does it work in ChrOS Player?

**Comment by kaden-rise** [comment]
@stulees This is the user's Display information:

arm Raspbian GNU/Linux 9.8 (stretch)
RisePlayerElectron 2019.07.09.14.41 Free
2-01-201907151935
Chromium 56.0.2924.87

This is my test Display's information:

64-bit Ubuntu 18.04.2 LTS
RisePlayerElectron 2019.06.18.17.05 Licensed
2-01-201907151935
Chromium 56.0.2924.87

I tested ChromeOS this morning and the same incorrect behavior occurs. Here's the information on my ChromeOS Display:

Chrome OS 11021.81.0
RisePlayer 2019.05.09.6291 Licensed
2-01-201904251346
Chrome 70.0.3538.110

**Comment by stulees** [comment]
Closing as @kaden-rise display is showing chart now. User display is offline
