### ISSUE TITLE
Pages with the Username/Password included in the URL no longer work

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/widget-web-page#118]
### What is the expected behavior?
Previously, using a URL with the username/password and action=login would work to show a page that required authentication.

### What is the actual behavior?
This stopped working in recent update. It still works in a browser.

### What steps can be taken to replicate the problem?
I can share the page that the user is trying to show to whoever takes this issue.

**Comment by stulees** [comment]
@robb-price Can you clarify 

> This stopped working in recent update. It still works in a browser.

There have been no significant changes to Web Page Widget in quite some time .

**Comment by stulees** [comment]
@robb-price As discussed over Slack, I provided you a JSFiddle to run that shows the users web page is only showing the login page. The demo is completely out of the context of Rise Vision, so this definitely indicates the user needs to make changes on their end in order for their page to bypass login screen when loaded into an iframe. Closing this, thanks.
