### ISSUE TITLE
spaces in the URL aren't accepted

### ISSUE THREAD

**Issue by nealg1** [Rise-Vision/widget-web-page#17]
Add a URL that contains a space in the name and press Save.

The Widget should automatically update the URL with a %20 once Save is pressed.

**Comment by alanclayton** [comment]
@donnapep @rodrigopavezi  @stulees is it possible for a url to have a space? Should we just close this as won't fix

**Comment by stulees** [comment]
@alanclayton Our validation prevents saving this unless the user chooses to not validate. I think this is a non issue and can close it.
