### ISSUE TITLE
Webpages overshoot when Interactivity is disabled and Zoom level is greater than 100%

### ISSUE THREAD

**Issue by alni** [Rise-Vision/widget-web-page#22]
When Interactivity is disabled and Zoom level is greater than 100% the iframe has a greater width and height the parent placeholder.

For webpages that dynamically adapts to fit this results in content being cut off or that the webpage does not correctly adapts to the correct size.

For example when setting the Zoom level to 200% the iframe containing the webpage has double the the displayed width and height resulting in only part of the content is visible.

One example of webpage that dynamically adapts to fit within the provided space is the Forecast.io "Forecast Embeds" widget. <http://blog.forecast.io/forecast-embeds/> (e.g. [http://forecast.io/embed/#lat=42.3583&lon=-71.0603&name=Downtown Boston](http://forecast.io/embed/#lat=42.3583&lon=-71.0603&name=Downtown Boston) )

To make such webpages to be correctly shown within the "Web Page Widget" the iframe containing the webpage must calcluate and set its width and height based on the Zoom Level.

I propose to add something like the following with the `zoomStyle` variable within the file `src/widget/webpage.js` near line 53:

    zoomStyle += "width: " + ((1 / zoom) * 100) + "%;" +
        "height: " + ((1 / zoom) * 100) + "%;";

**Comment by stulees** [comment]
@alni Thanks for raising this issue. Your proposal looks good. To move this forward, you need to fork this repo and initiate a pull request for this change to be considered. Also, we try to always accompany any code change with appropriate tests (unit and/or e2e), so please include any tests that are applicable and possible in your PR. Thanks!

**Comment by stulees** [comment]
@alni This fix has been implemented. As I mentioned on your pull request, to get the latest changes that include your fix you will have to re-add the widget to your presentation. Thanks
