### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by jbearden0** [Rise-Vision/widget-web-page#25]
When installing on Ubuntu 14.04, "npm install" failed with the following error:

 npm ERR! peerinvalid The package chai does not satisfy its siblings' peerDependencies requirements!
 npm ERR! peerinvalid Peer chai-as-promised@4.1.1 wants chai@>= 1.7.0 < 2
 npm ERR! peerinvalid Peer karma-chai@0.1.0 wants chai@*
 npm ERR! peerinvalid Peer sinon-chai@2.7.0 wants chai@>=1.9.2 <3

I don't know anything about node.js or any of this stuff, but adding

 "chai": "~1.9.2",

to the top of the devDependencies section of package.json seems to have resolved the issue.

**Comment by jbearden0** [comment]
I just submitted a pull request that fixes this issue, among other things.

**Comment by stulees** [comment]
@jbearden0 As mentioned on your pull request, the missing Chai dependency issue has been fixed. Thanks
