### ISSUE TITLE
Testing Issue

### ISSUE THREAD

**Issue by jbearden0** [Rise-Vision/widget-web-page#26]
When running gulp test on Ubuntu 14.04 I get:

[12:53:10] Starting '09e76ff1-b60d-11e4-be04-f539312f8ab7:runCasperTests'...

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)

There are multiple events.js files, so I'm not sure which one to look at to try and figure out what the problem is.

**Comment by stulees** [comment]
@jbearden0 Thanks for raising this issue. It is likely an Ubuntu 14.04 and Node issue and not specific to any code pertaining to this repo. I suggest investigating any similar issues other people have had with this combination of Ubuntu version and Node version. It may be that you will have to make fixes to your own local setup. Thanks

**Comment by alanclayton** [comment]
@stulees should this be closed?

**Comment by stulees** [comment]
@alanclayton Yes this can be closed.
