### ISSUE TITLE
Interactivity does not work when more than 1 webpage widget or presentation is in schedule.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/widget-web-page#31]
You can't interact with the Web Page Widget if the Playlist contains more than one instance of the Widget

1. Add two instances of the Web Page Widget to a Playlist. 
2. Configure both to be interactive.
3. Run the Presentation
Result:
You are unable to interact (touch) links in either instance of the Web Page Widget. If you remove one instance of the Widget and republish your Presentation, you'll be able to interact with the remaining instance. 

The same result is achieved if you create multiple presentations with individual web pages and schedule them.

How it should work:
You should be able to interact with the Web Page from either instance of the Widget. 

Link to Presentation: http://preview.risevision.com/Viewer.html?type=presentation&id=9e0320d5-e9a2-4aac-8d09-2cfd2bef91f9
OS: ALL
Chrome Ver: Version 40.0.2214.111 (64-bit)

**Comment by mmeiers** [comment]
I can confirm the same thing Blake is seeing.
Additionally I noticed that linking two urls into a schedule will provide similar results.
So the issue may not be limited to web page widget.

**Comment by mmeiers** [comment]
@stulees Do you think this bug belongs with this widget? Or do you think it should go somewhere else?

**Comment by stulees** [comment]
@mmeiers I haven't investigated it yet, have you or Blake seen similar results described in this issue with other Widgets? If so, then I think this bug belongs to Viewer. Thanks

**Comment by stulees** [comment]
@btfrise I wasn't able to reproduce this issue. My presentation is here - http://rva.risevision.com/#/PRESENTATION_MANAGE/id=62cfb4e3-7a8f-41a0-9c23-a616bf8dc670?cid=30007b45-3df0-4c7b-9f7f-7d8ce6443013

Given how old the issue is, it may have been a Viewer issue and has since been fixed. I think we can close this. Thanks @alanclayton FYI

**Comment by btfrise** [comment]
Was not able to replicate in either the production v3 installer or the Electron player. Closing.
