### ISSUE TITLE
There is a visible flicker when transitioning from one web-page-widget item to another in a placeholder

### ISSUE THREAD

**Issue by mfisher11** [Rise-Vision/widget-web-page#38]
Steps to reproduce:
1. Assign (or preview) a presentation containing multiple web page widgets in a single placeholder.

Result:
When the display moves from one item to the next, there is a visible flicker.
This does not happen in the web page gadget.

How it should work:
The transition should be smoother.  Like the gadget.

Link to Presentation:
http://rva.risevision.com/#/PRESENTATION_MANAGE/id=5f56612c-2ac4-4a2b-a627-be6266208ee8?cid=e514fd51-fadd-4e19-94af-f92549772c7f

OS:
Linux (Ubuntu and Lubuntu 14.04)

Chrome Ver:
This happens in the latest stable version with CAP and the bundled version with the new Rise Player.

**Comment by ByronDarlison** [comment]
@alanclayton what's the plan for this defect? Thanks

**Comment by alanclayton** [comment]
@ByronDarlison this occurs because the web page is unloaded when it is not visible in the Presentation to prevent audio that may exist on the page from running in the background. We are addressing this scenario with the card here, https://trello.com/c/fjsiqtZz/1502-2-handle-scenario-where-audio-is-on-page

**Comment by ByronDarlison** [comment]
@alanclayton thanks. To confirm, you think you can fix this, do I have that right? Thanks

**Comment by alanclayton** [comment]
@ByronDarlison That is correct. Thanks

**Comment by alanclayton** [comment]
Fixed with latest release.
