### ISSUE TITLE
Horizontal Scroll properties not reflecting on preview

### ISSUE THREAD

**Issue by hcs0** [Rise-Vision/widget-web-page#40]
**How to replicate**
For reference go to https://rva.risevision.com/#/PRESENTATION_MANAGE/id=2c86a5c2-1452-41b4-a7c0-0e726df89923?cid=960b72df-9af7-476b-8a47-b67ded4c779d
The presentation contains four widgets:
2 x Web Page Widget to a user website
2 x Web Page Widget to the RV website to show if issue is contained within the user's website

**Expected Results**
When editing the horizontal properties of the Webpage Widget, I am able to navigate to another part of the website.

**Actual Results**
On editing the horizontal scroll properties on both websites, I am not able to view or navigate to other parts of the webpage within that widget.
On editing the vertical scroll properties on both websites, I am able to view or navigate other parts of the website within that widget.
**This is reflected in the Display**

The best way to see it is to configure the horizontal scroll properties within that presentation.

@stulees Can you let me know what your thoughts are on this and if you need anything further? Rather than listing out the steps, I've added in the actual presentation so you can copy this presentation and start tweaking the horizontal settings.

**Comment by lapinnoir** [comment]
https://app.intercom.io/a/apps/d85f4ah4/inbox/conversation/1727542459

**Comment by robb-price** [comment]
@lapinnoir Is the bug here that the website in the 2nd and 4th Placeholders don't show at all?

**Comment by alanclayton** [comment]
@hcs0 To confirm, this only occurs in Preview per the issue title?

**Comment by hcs0** [comment]
@alanclayton This happens upon preview and it is reflected in the Display. I'll make a note of this in the original issue

**Comment by donnapep** [comment]
@hcs0 Is the Presentation listed in the bug report still available? I can't seem to find it. Thx.

**Comment by hcs0** [comment]
@donnapep Sorry, I saw this just then.  Recreating presentation now

**Comment by hcs0** [comment]
@donnapep Looks like the issue is fixed - top is 100px horizontal scroll and the bottom is 300px horizontal scroll https://apps.risevision.com/editor/workspace/3b731626-5604-40fa-9165-405a77e08de9/?cid=960b72df-9af7-476b-8a47-b67ded4c779d

I can close this issue now

**Comment by donnapep** [comment]
@hcs0 Before closing, would you mind trying with our new version of the Widget to be sure?

Here are the URLs:
http://s3.amazonaws.com/widget-web-page-test/stage-1-dev/1.0.0/dist/widget.html
https://s3.amazonaws.com/widget-web-page-test/stage-1-dev/1.0.0/dist/settings.html

Or you can make changes to this Presentation - http://goo.gl/9jrj9l

Thx!

**Comment by hcs0** [comment]
@donnapep Yep it works - thanks

**Comment by donnapep** [comment]
@hcs0 Great. Thx!
