### ISSUE TITLE
Web-Page-Widget editor redirect 

### ISSUE THREAD

**Issue by SpencerHawkswell** [Rise-Vision/widget-web-page#60]
When adding a web page URL (www.DonaldJTrump.com) to the web-page-widget, the website takes over and redirects not only the display in preview but also the editor. 

This is a problem because users may add a website, such as the Trump website, and it mayl load faster than they can remove it fro the editor. This will result in having to delete the presentaton or at least quite a bit of frustration.

**link to the presentation in the editor**
https://apps.risevision.com/editor/workspace/d4e2d592-b5c3-4327-bedc-232f50f6fda2/?cid=f114ad26-949d-44b4-87e9-8528afc76ce4

**Link to the Preview**
http://preview.risevision.com/?type=presentation&id=d4e2d592-b5c3-4327-bedc-232f50f6fda2

**Link to Trumps website (The one being used)**
http://preview.risevision.com/?type=presentation&id=d4e2d592-b5c3-4327-bedc-232f50f6fda2

**Recording of the issue**
http://recordit.co/VHs4zse70a

A way to remove the problem is to quickly delete _placeholder 6_ in the presentation, before the Trump website can load.

To recreate the problem, just place the Trump website in the web-page-widget and save. The problem seems to occur regardless of the web-page-widget settings.

**Comment by stulees** [comment]
@SpencerHawkswell This has been fixed with PR #62 , closing, thanks.
