### ISSUE TITLE
Widget shows iframe error, but the page shows in a Presentation without issue

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/widget-web-page#72]
<b>How it works now</b>
1. Using <a href="https://apps.risevision.com/editor/workspace/7d34b9ea-4bf6-4840-8b8e-898813a41e05/?cid=556323b8-984c-4127-aa08-4d73d019bcb8">this Presentation</a>, notice that when you open the Web Page Widget settings, you get the message <i>The owner of the Web Page at the URL provided does not allow the page to be embedded within an iFrame. If possible, please contact the Web Page owner to discuss X-Frame-Options.</i> for the page.
2. Notice that the Presentation plays fine in preview, and on a Display.

<b>How it should work</b>
If the page shows no problem, no error should appear in the Widget settings.

**Comment by robb-price** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(1) Issue 72: IFrame error shows in Widget settings, but the page runs fine.](https://trello.com/c/t1Ro5Jp9/3333-1-issue-72-iframe-error-shows-in-widget-settings-but-the-page-runs-fine)

**Comment by stulees** [comment]
@robb-price Fixed with #73 , closing, thanks
