### ISSUE TITLE
Videos displayed in Web Page Widget on a Display to not autoplay.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/widget-web-page#76]
**How to recreate**
1. Add a page to the Webpage Widget that has video that automatically starts in the browser (e.g. https://cedarfalls.viebit.com/player_live.php?hash=3666443c-3b31-4c25-b992-22b0f5193165).
2. Save the Presentation and assign to a Display.

**What happens?**
The video does not autostart in the web page widget when scheduled on a display.

**What should happen?**
Users should be given the option of auto starting videos.

**Comment by sheadarlison** [comment]
@btfrise I think it might be flash or use a plugin when you run the video on a display it says couldn't load plugin. If you try loading the video in chromium on your laptop it won't work.

**Comment by btfrise** [comment]
@sheadarlison Got it, flash based stream, I'll close!
