### ISSUE TITLE
When Webpage blocks x-frame embedding, no error message is shown.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/widget-web-page#83]
***How to recreate***
1. Add the Web Page Widget to a Presentation
2. Add the URL to a web page that disables x-frame embedding
3. Preview or assign to Display

**What happens**
Nothing appears. We get a "Refused to display 'http://www....' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

**What should happen**
The Web Page Widget should warn that this page disables embedding via x-frame and should not allow it's use.

**Comment by btfrise** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(1) Issue 83 When Webpage blocks x-frame embedding, no error message is shown.](https://trello.com/c/cfaLYupG/8113-1-issue-83-when-webpage-blocks-x-frame-embedding-no-error-message-is-shown)

**Comment by sheadarlison** [comment]
@btfrise we already do this?

![screen shot 2018-06-05 at 5 19 35 pm](https://user-images.githubusercontent.com/9273546/41003398-aacdb298-68e4-11e8-9441-33b602562603.png)
