### ISSUE TITLE
Page refresh not consistent.

### ISSUE THREAD

**Issue by santiagonoguez** [Rise-Vision/widget-web-page#88]
**What happens**
The web page configured on the widget does not reload every minute as it's configured. The reload interval seems to grow longer and longer with time.

**What should happen**
The web page configured on the widget should be reloaded every minute. This should be confirmed on the HTTP server access log.

**How to reproduce**
1. In a media player, open a command line window and change to a test directory.
1. Run a simple python based HTTP server:
      $ python -m SimpleHTTPServer 8000
1. Create a simple HTTP page ( test.html )
1. From a different command line window, test it works:   $ curl http://localhost:8000/test.html
1. Check that the local HTTP server records the access.
1. Open a web browser, open apps.risevision.com and go to a company that allows widget-web-page.
1. Create a presentation that has a single placeholder and a web-page widget.
1. Set http://localhost:8000/test.html as URL, uncheck remove validation, set refresh interval to 1 minute, uncheck unload web page. Save
1. ( optional ) On the playlist item set Play Until Done. It fails with or without a time set here. The original reported problem has 15 seconds set here.
1. Create a display if there is not one available.
1. Create a schedule linking the display and the presentation. The presentation can have Play Until Done set or not. The original problem has 3 presentations set to 2, 10 and 3 seconds. The second and third presentation point to web pages with the configuration above.
1. Run Rise Vision Player and check the interval between page requests in the HTTP server console. Intervals grow larger as time passes by. If a schedule with 2 presentations is created instead, irregular and inconsistent intervals are shown also.

**Comment by robb-price** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(3) User Blocked: Issue 88 - Web Page Widget Refresh Inconsistent](https://trello.com/c/UBa1zZ5z/8288-3-user-blocked-issue-88-web-page-widget-refresh-inconsistent)

**Comment by robb-price** [comment]
User confirms that this corrected the issue. Closing the Issue.
