### ISSUE TITLE
"Enable cache buster (recommended)" is not user friendly or descriptive.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/widget-web-page#95]
A normal user would have no idea what "Enable cache buster (recommended)" does, why it's recommended, or why they should select it.

**Comment by sheadarlison** [comment]
@btfrise have you gotten questions about this from customers and if so can you please link the tickets to the Trello card. 

Also do you have a recommendation on what the message should say? 

Thanks

**Comment by sheadarlison** [comment]
https://trello.com/c/ZyE4isZx/5745-widget-web-page-issue-95
