### ISSUE TITLE
Certain combinations of characters freezing browser tab when entered into URL bar

### ISSUE THREAD

**Issue by kaden-rise** [Rise-Vision/widget-web-page#98]
##### What is the expected behavior?
Users should be able to enter anything into the URL bar in the web page widget settings

##### What is the actual behavior?
Entering certain characters into the URL bar causes the browser tab to freeze in Google Chrome (Not tested in other browsers)

##### What steps can be taken to replicate the problem? 
1. Add a Web Widget to a placeholder
2. Enter gibberish such as "dsfjdsfdskfjdskjfdskljf" into the URL bar.

**Comment by kaden-rise** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #98 - Certain combinations of characters freezing browser tab when entered into URL bar](https://trello.com/c/BGK78EtV/8894-issue-98-certain-combinations-of-characters-freezing-browser-tab-when-entered-into-url-bar)

**Comment by santiagonoguez** [comment]
Solution now in master branch and deployed.
